#docker run --name world_db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql
version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    container_name: app


  # db is is db folder

  db:
    build: db/.
    #command: --authentication_policy
    restart: unless-stopped
    container_name: db
    image: mysql:latest
    ports:
      - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: world
        MYSQL_USER: mysql
        MYSQL_PASSWORD: pass
